project:
  type: book

book:
  chapters:
    - index.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd
    - chapters/references.qmd
  appendices: 
    - appendices/appendix-a.qmd

bibliography: files/references.bib

format:
  pdf:
    documentclass: report
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: false
    toc-title: Table of contents

crossref:
  fig-title: Figure # figure name in the caption
  fig-prefix: Figure # figure name in the text
  tbl-title: Table # table name in the caption
  tbl-prefix: Table # table name in the text
  lst-title: Code # code name in the caption
  lst-prefix: Code # code name in the text
  eq-title: Equation # equation name in the caption
  eq-prefix: Equation # equation name in the text
  
filters:
  - first-line-indent

department: Dipartimento di Psicologia dello Sviluppo e della Socializzazione
degree: Corso di laurea magistrale in Psicologia Clinica dello Sviluppo
thesis: Tesi di laurea magistrale
title-ita: Titolo tesi in italiano
title-eng: Titolo tesi in Inglese
supervisor-prefix: Relatore
supervisor-name: Prof. Gianmarco Altoè
cosupervisor-prefix: Correlatore
cosupervisor-name: Dr. Filippo Gambarota
student-prefix: Laureando
student-name: Filippo Gambarota
matricola-prefix: Matricola
matricola: 1111111
academic-year-prefix: Anno Accademico
academic-year: 2024/2025